# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

In [1]:
import numpy as np

## Personal Practices

### 3D Arrays

In [29]:
# 3D array, consiting of 3 lists nested.

## view the coloured [ ] for identifying the differenet nested lists within the numpy array

a = np.array( [ [[1,2],[3,4]] , [[5,6],[7,8]] ])

print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Get specifc element ( Work from the outside IN )


## Get value 4, from the 1st list, 2nd row, 2nd element (remember indexes begin on 0)
print(a[0,1,1])

## Get value 7
print(a[1,1,0])

4
7


#### 2. Create a null vector of size 10 (★☆☆)

To create a Matrix in numpy, or a vector, you can use designated functions/methods to produce the formatted vecter

### Martixs and Arrays


In [23]:
# Null Vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Null Vector of size 2 by 3
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# All 1's matrix

np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [57]:
# Any other number input to the whole matrix

np.full( (2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [58]:
# Use a range value to produce an array of the desired values

np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [36]:
# Produce an array resembling the shape of previously created array

b = np.full_like(a,99)
print(b)

c = np.full(a.shape, 88)
print(c)

[[[99 99]
  [99 99]]

 [[99 99]
  [99 99]]]
[[[88 88]
  [88 88]]

 [[88 88]
  [88 88]]]


In [38]:
# Random deicmal numbers in an array

## Produces a matrix of 4 rows, 2 columns with random float values

np.random.rand(4,2)

array([[0.90687082, 0.77314671],
       [0.87256902, 0.63953659],
       [0.9490092 , 0.03531488],
       [0.1852981 , 0.65806201]])

In [43]:
# Random integer values

## first values indicates value range

np.random.randint(2,8, size=(3,3))

array([[3, 7, 3],
       [2, 5, 3],
       [4, 4, 7]])

In [45]:
# THe indentify Matrix

# Will always produce a matrix in a square format, with the rows equal your entered value

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
# Repeat an array 

arr = np.array( [ [1,2,3] ] )

## Producing a 2D array 

r1 = np.repeat(arr, 3, axis = 0)

## Repating the inner list of the array 3 times, across the 0 axis (rows value)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [50]:
nvector = np.zeros(10)

nvector[4] = 1

print(nvector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [56]:
vector2 = np.arange(10, 50)
print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [73]:
print(vector2[::-1])

print(vector2[3:10:2])

print(vector2[5::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[13 15 17 19]
[15 14 13 12 11 10]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [63]:
matrix1 = np.arange(9).reshape(3, 3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
np.arange(35).reshape(7,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [83]:
vector3 = [1,2,0,0,4,0]
print(vector3)


## numpy function np.nonzero()

print(np.nonzero(vector3))


[1, 2, 0, 0, 4, 0]
(array([0, 1, 4]),)


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [91]:
matrix2 = np.random.randint(100, size=(3,3,3))

print(matrix2)


[[[15 63  8]
  [21 38 30]
  [68  3 91]]

 [[25 38 64]
  [23 89 16]
  [ 3 36 42]]

 [[53 58 54]
  [62 94 68]
  [82 41 95]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
matrix3 = np.random.random(size=(10,10))

print(matrix3)

print(matrix3.min() , matrix3.max())


[[0.03069867 0.51197573 0.5219453  0.3691903  0.81364175 0.71850227
  0.66662746 0.3511726  0.04234541 0.84815298]
 [0.46087053 0.89160496 0.34061839 0.52996452 0.93302082 0.59567818
  0.74409505 0.1967939  0.54115175 0.95261192]
 [0.23075957 0.84636942 0.34509451 0.40587227 0.24556737 0.14524963
  0.30476882 0.92748916 0.54760303 0.56922886]
 [0.65363918 0.94920189 0.26250787 0.51341488 0.56523794 0.35024712
  0.10657049 0.64394073 0.05614483 0.10933369]
 [0.19611375 0.60187106 0.3823532  0.04554972 0.21933218 0.11294334
  0.47285124 0.99365288 0.6805508  0.5379466 ]
 [0.9244753  0.62322461 0.09906245 0.36520697 0.26473521 0.36473329
  0.20151014 0.69298327 0.29541106 0.72568802]
 [0.3478316  0.84112297 0.80759864 0.7614638  0.28995956 0.59966365
  0.10442375 0.45692361 0.72888982 0.72666153]
 [0.38095589 0.38275485 0.45732077 0.28565941 0.13363588 0.90834849
  0.47111535 0.42525247 0.82070426 0.55040192]
 [0.97840476 0.62963663 0.55380406 0.04438646 0.9312142  0.78978034
  0.4934529 

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [94]:
vector4 = np.random.random(30)

print(vector4)

print(vector4.mean())

[0.08050876 0.29880341 0.72232605 0.66942582 0.22432425 0.82208199
 0.94399693 0.10817136 0.84618821 0.8591738  0.88397538 0.52226834
 0.48965087 0.65590254 0.09678459 0.07666485 0.04348349 0.83238652
 0.68896188 0.54899596 0.97382222 0.79113946 0.88185066 0.09259958
 0.10406498 0.20809982 0.75716705 0.21348206 0.39929735 0.23755659]
0.5024384918902954


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [103]:
array2 = np.ones( (3,3) )
print(array2)



array2[1,1] = 0

print(array2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:


array3 = array2.copy()

print(array3)

z = np.zeros( (3,3) )

print(z[0:3])

array3[0:3,0:3] = z

print(array3)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [121]:
# nan is Null

null
False
False
null
True
False

NameError: name 'null' is not defined

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [125]:
import numpy as np

matrix4 = np.zeros((5, 5))
matrix4[np.arange(1, 5), np.arange(0, 4)] = [1, 2, 3, 4]
print(matrix4)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [128]:
matrix5 = np.zeros( [6,7,8] )


index = np.unravel_index(100, matrix5.shape)
print(index)


(np.int64(1), np.int64(5), np.int64(4))


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [131]:
matrix7 = np.arange(25).reshape([5,5])
matrix7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [132]:
matrix6 = np.arange(25).reshape((5, 5))
normalized_matrix = (matrix6 - matrix6.min()) / (matrix6.max() - matrix6.min())
print(normalized_matrix)

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [135]:
array4 = np.arange(10)
print(array4)

array4[(array4 > 3) & (array4 < 8)] *= -1

print(array4)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 18. How to round away from zero a float array ? (★☆☆)

#### 19. Find common values between two arrays? (★☆☆)

In [141]:
array6 = np.arange(10)
array7 = np.arange(6,15)

array6 , array7

np.intersect1d(array6,array7)

array([6, 7, 8, 9])

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [146]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/bs/_y1b6rb96rb21tm4p3r5fpz80000gn/T/ipykernel_5981/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_


#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [150]:
vector5 = np.arange(0,1)
vector5

array([0])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [168]:
vector6 = np.sort((np.random.randint(0,10, size=10)))

vector6


array([0, 1, 1, 2, 2, 2, 5, 6, 8, 9])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [174]:
vector7 = np.random.randint(0,10, size=10)
vector8 = np.random.randint(0,10, size=10)

np.array_equal(vector7 , vector8)

False

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [198]:
vector9 = np.sort(np.random.randint(0,10, size=10))
print(vector9)

vector9[vector9 == vector9.max()] = 0
print(vector9)

[1 3 4 7 7 8 8 8 9 9]
[1 3 4 7 7 8 8 8 0 0]


#### 26. Find the closest value to random element in a vector? (★★☆)

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

#### 28. Sort an array by the nth column? (★★☆)

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 31. Swap two rows of an array? (★★★)

#### 32. How to negate a boolean value inside an array? (★★★)

#### 33. Find the most frequent value in an array?

#### 34. Get the n largest values of an array (★★★)

#### 35. Extract unique rows from a two dimensional array? (★★★)